export { ResultCalculator } from "./result-calculator";
export { calculateSetup } from "./calculation/calculateSetup";
export {
  ArtifactCalc,
  CharacterCalc,
  CharacterData,
  CharacterReadData,
  GeneralCalc,
  WeaponCalc,
  type ArtifactSetBonus,
} from "./common-utils";

export {
  AttackBonusesControl,
  ResistanceReductionControl,
  TotalAttributeControl,
  TrackerControl,
  AppliedBonusesGetter,
  BareBonusGetter,
  InputProcessor,
} from "./input-processor";

export * from "./calculation-utils/getDataOfSetupEntities";
export * from "./constants";

export type { CalcAtomicRecord, CalcItemRecord, TrackerResult } from "./input-processor";
export type {
  ActualAttackPattern,
  AmplifyingReaction,
  AppArtifact,
  AppCharacter,
  AppMonster,
  AppWeapon,
  AppliedAttackBonus,
  AppliedAttributeBonus,
  AppliedBonuses,
  ArtifactAttribute,
  ArtifactModifierDescription,
  ArtifactType,
  AttackBonusKey,
  AttackBonusType,
  AttackBonuses,
  AttackElement,
  AttackPattern,
  AttackReaction,
  AttributeStat,
  TalentCalcItem,
  CalculationAspect,
  CalculationFinalResult,
  CalculationFinalResultGroup,
  CalculationFinalResultItem,
  CharacterBuff,
  CharacterDebuff,
  CharacterMilestone,
  CoreStat,
  ElementType,
  Level,
  LevelableTalentType,
  ModInputConfig,
  ModInputType,
  ModifierAffectType,
  NormalAttack,
  NormalAttacksConfig,
  OptimizerAllArtifactModConfigs,
  OptimizerArtifactModConfigs,
  OptimizerExtraConfigs,
  QuickenReaction,
  ReactionType,
  ResistanceReduction,
  ResistanceReductionKey,
  TalentType,
  TotalAttribute,
  TransformativeReaction,
  WeaponBuff,
  WeaponType,
} from "./types";
