export * from "./bonus-spec";
export * from "./common-specs";
export * from "./effect-condition-specs";
export * from "./effect-extra-spec";
export * from "./effect-max-spec";
export * from "./effect-stack-spec";
export * from "./effect-value-spec";
export * from "./modifier-specs";
export * from "./penalty-spec";
